baseurl = "/"
languageCode = "en-us"
title = "Max Malm"
theme = "benclean"
MetaDataFormat = "toml"
Paginate = 10

[params]
  Github = "benjick"
  Facebook = "maxmalm"
  Twitter = "benjick"
  GPlus = "MaxMalm"

[permalinks]
  blog = "/:year/:month/:slug/"
